root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  entrypoint = ["./tmp/api"]
  delay = 200
  exclude_dir = ["tmp", "vendor", ".git"]
  include_dir = ["cmd", "internal"]
  include_ext = ["go"]
  stop_on_error = true
  send_interrupt = true

[env]
  APP_ENV = "dev"

[log]
  time = true
