services:
  db:
    image: postgres:16
    container_name: eventhub-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-eventhub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eventhub}
      POSTGRES_DB: ${POSTGRES_DB:-eventhub}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - eventhub_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventhub -d eventhub"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7-alpine
    container_name: eventhub-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly","yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  eventhub_pgdata:
  redis-data:
