global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "eventhub-api"
    static_configs:
      - targets: ["host.docker.internal:8080"] 

  - job_name: "eventhub-worker"
    static_configs:
      - targets: ["host.docker.internal:8081"] # worker health port
